version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@0.0.4
workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: '${ECRURL}'
          repo: 'demo1'
          region: 'east-2'
          aws-access-key-id: '${accesskey}'
          aws-secret-access-key: '${awsaccesskey}'
          
